export const DESTINATION_COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Portugal",
  "Ireland",
  "New Zealand",
  "Japan",
  "South Korea",
  "Singapore",
  "United Arab Emirates",
  "Qatar",
  "Saudi Arabia",
  "Malaysia",
  "Romania",
  "Bulgaria",
  "Croatia",
]

export type DestinationCountry = (typeof DESTINATION_COUNTRIES)[number]

export const COUNTRY_FLAGS: { [key: string]: string } = {
  "United States": "🇺🇸",
  "United Kingdom": "🇬🇧",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Italy: "🇮🇹",
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  Sweden: "🇸🇪",
  Portugal: "🇵🇹",
  Ireland: "🇮🇪",
  "New Zealand": "🇳🇿",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Singapore: "🇸🇬",
  "United Arab Emirates": "🇦🇪",
  Qatar: "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  Malaysia: "🇲🇾",
  Romania: "🇷🇴",
  Bulgaria: "🇧🇬",
  Croatia: "🇭🇷",
  Bangladesh: "🇧🇩",
  India: "🇮🇳",
  Pakistan: "🇵🇰",
  Nepal: "🇳🇵",
  "Sri Lanka": "🇱🇰",
  Philippines: "🇵🇭",
  Indonesia: "🇮🇩",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  China: "🇨🇳",
  Turkey: "🇹🇷",
  Nigeria: "🇳🇬",
  Kenya: "🇰🇪",
  Egypt: "🇪🇬",
  Jordan: "🇯🇴",
  Lebanon: "🇱🇧",
  Brazil: "🇧🇷",
  Mexico: "🇲🇽",
  Argentina: "🇦🇷",
  Switzerland: "🇨🇭",
  Belgium: "🇧🇪",
  Norway: "🇳🇴",
  Denmark: "🇩🇰",
  Finland: "🇫🇮",
  Austria: "🇦🇹",
  Poland: "🇵🇱",
  Greece: "🇬🇷",
  Russia: "🇷🇺",
  "South Africa": "🇿🇦",
  Kuwait: "🇰🇼",
  Bahrain: "🇧🇭",
  Oman: "🇴🇲",
}

export const ALL_COUNTRIES = Object.keys(COUNTRY_FLAGS)

export const COUNTRY_CODES: { name: string; dial: string }[] = [
  { name: "Bangladesh", dial: "+880" },
  { name: "India", dial: "+91" },
  { name: "Pakistan", dial: "+92" },
  { name: "Nepal", dial: "+977" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Philippines", dial: "+63" },
  { name: "Indonesia", dial: "+62" },
  { name: "Thailand", dial: "+66" },
  { name: "Vietnam", dial: "+84" },
  { name: "China", dial: "+86" },
  { name: "United States", dial: "+1" },
  { name: "United Kingdom", dial: "+44" },
  { name: "Canada", dial: "+1" },
  { name: "Australia", dial: "+61" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Italy", dial: "+39" },
  { name: "Spain", dial: "+34" },
  { name: "Netherlands", dial: "+31" },
  { name: "Sweden", dial: "+46" },
  { name: "Portugal", dial: "+351" },
  { name: "Ireland", dial: "+353" },
  { name: "New Zealand", dial: "+64" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "Singapore", dial: "+65" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Qatar", dial: "+974" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "Malaysia", dial: "+60" },
  { name: "Romania", dial: "+40" },
  { name: "Bulgaria", dial: "+359" },
  { name: "Croatia", dial: "+385" },
  { name: "Turkey", dial: "+90" },
  { name: "Nigeria", dial: "+234" },
  { name: "Kenya", dial: "+254" },
  { name: "Egypt", dial: "+20" },
  { name: "Jordan", dial: "+962" },
  { name: "Lebanon", dial: "+961" },
  { name: "Brazil", dial: "+55" },
  { name: "Mexico", dial: "+52" },
  { name: "Argentina", dial: "+54" },
  { name: "Switzerland", dial: "+41" },
  { name: "Belgium", dial: "+32" },
  { name: "Norway", dial: "+47" },
  { name: "Denmark", dial: "+45" },
  { name: "Finland", dial: "+358" },
  { name: "Austria", dial: "+43" },
  { name: "Poland", dial: "+48" },
  { name: "Greece", dial: "+30" },
  { name: "Russia", dial: "+7" },
  { name: "South Africa", dial: "+27" },
  { name: "Kuwait", dial: "+965" },
  { name: "Bahrain", dial: "+973" },
  { name: "Oman", dial: "+968" },
]

export const VISA_TYPES = [
  "Work Permit Visa",
  "Student / Study Visa",
  "Tourist / Visit Visa",
  "Business Visa",
  "Medical Visa",
  "Family / Spouse Visa",
  "Transit Visa",
  "Permanent Residency",
  "Diplomatic Visa",
]

export const PASSPORT_TYPES = ["Ordinary", "Official", "Diplomatic"]

export const VISIT_PURPOSES = ["Tourism", "Family Visit", "Transit"]
